### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by huhuegg** [nmdias/DefaultsKit#10]
[Leak Checks] 
 538.14 KB      85.4%	9255	 	                             0x100829463 **DefaultsKit** 
 538.14 KB      85.4%	9255	 	                              JSONDecoder.decode<A>(_:from:)
 279.39 KB      44.3%	4772	 	                               +[NSJSONSerialization JSONObjectWithData:options:error:]

**Comment by nmdias** [comment]
Hi @huhuegg,

Thanks for contributing. Can you provide a screenshot of the reference pointers so I can have a better look?

If there is a leak, it’s probably under the JSONDecoder. Defaults uses a single class and at most a lazy singleton, there are no fancy references between different objects.

Cheers
