### ISSUE TITLE
Support Implicit Member Expression

### ISSUE THREAD

**Issue by KyoheiG3** [nmdias/DefaultsKit#13]
Hi @nmdias 

Can `Key` class inherit a class like following, for example?
```swift
public class AnyKey {}

public final class Key<ValueType: Codable>: AnyKey {}
```

This makes it possible to do following.
```swift
extension AnyKey {
    static let key = Key<String>("someKey")
}

defaults.set("Codable FTW 😃", for: .key)
```

My goal is like #9.

Thanks.

**Comment by nmdias** [comment]
Thank you for the suggestion @KyoheiG3, it worked out really well 😃
