### ISSUE TITLE
How to read it out from different View Controller?

### ISSUE THREAD

**Issue by chingyu01** [nmdias/DefaultsKit#14]
Dears:

I don't know how to read it back at different view controllers. For example: I save my data at login view controller, and I need to read it out at Friends View Controller. How do I do? Thanks!

**Comment by nmdias** [comment]
Hi,

The same way you would read it at the login controller. Just call `defaults.get(for: key)` wherever you want.

Cheers

**Comment by chingyu01** [comment]
Thanks! But my problems are like these as below:

I can't find key , and read it back at other sides....

<img width="760" alt="iconcollectionviewcontroller_swift_ _edited-2" src="https://user-images.githubusercontent.com/35747358/41019298-98fbc54e-6990-11e8-849a-392cc1e6b2bd.png">

**Comment by nmdias** [comment]
Hi. Your iconKey is defined in a different scope. Check the closing bracket just above the error.

Either move it inside the brackets above, or move the definition of the iconKey out of those brackets scope.

Does that help?

Cheers

**Comment by chingyu01** [comment]
Thank you so much!!!
