### ISSUE TITLE
Missing DefaultsKey

### ISSUE THREAD

**Issue by wdcurry** [nmdias/DefaultsKit#16]
Testing out the repo, looks great! Of course, immediately set out to create default keys, as that just feels right. Noted the Defaults.swift file is missing (that *is* in the demo).
ps: naming the file to match only makes sense too ;)

Cheers!

**Comment by nmdias** [comment]
Hi @wdcurry 

I'm not sure I'm following. Are you saying the the Defaults.swift file is missing? It doesn't appear to be missing. What Demo are you referring to?

About naming the file to match, are you suggesting renaming Defaults.swift as DefaultsKit.swift? If that's the case, unless it's not possible or sufficient, I instinctually attribute the name of the file the same as the "main" class/struct/type that represents it.

Thanks

**Comment by wdcurry** [comment]
Sorry if i wasn't more clear: the installed pod folder does not include the Defaults.swift file, thus cannot find DefaultsKey for import. I used the standard "pod 'DefaultsKit'" within my podfile.

And my bad (partially ;) ) .. re the file name comment. I was mid-multiple-tasks. I agree with your instincts, i just missed the main class below. My style is one-class/one-file thus my instinctual comment and mistake 😇 🤓 🙏

**Comment by nmdias** [comment]
This is odd... 🤔 I'm unable to reproduce this error (I'm on Xcode 9.4.1 right now). 

@wdcurry would you mind verifying if you're using version 0.0.9? Also, could you run `pod try DefaultsKit` in the terminal and give the unit tests a run?

Thanks

**Comment by wdcurry** [comment]
Have you installed it from scratch into a new project via pod install? This is the acid test for such things. I noted the copyright for your demo was 2017-18 while the installed pod was only 2017. The pod itself is out of sync it seems.

**Comment by nmdias** [comment]
I just tried in a newly created project, with the single Pod and the following Podfile.

```sh
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Test' do
  pod 'DefaultsKit'
end
```

**Comment by wdcurry** [comment]
The only diff is that i don't predefine the iOS platform in the podfile. Oh well, i just manually reset the repo with the newer file, so it's all good. This was more a minor FYI, just in case. cheers!
