### ISSUE TITLE
Using PLIST encoder for defaults

### ISSUE THREAD

**Issue by danlozano** [nmdias/DefaultsKit#2]
Hi!

Great idea/framework. Can't wait to use Codable everywhere in my projects.

Looked over the code and thought of something.

- Why are you using JSONEncoder/Decoder? Since you are storing un UserDefaults, you are converting to JSON data then storing. BUT UserDefaults is a PLIST, so it accepts any value that is a PLIST. You could convert the model you want to save with the PLIST decoder/encoder and not worry about changing back and forth from Data.

Maybe both could be an option. Just curious. 👍

**Comment by nmdias** [comment]
Hi @danlozano :)

I'm not sure what you mean when you say that UserDefaults accepts a plist value. How would you store a plist value in UserDefaults, without converting it to a Data object first then back? 

Can you provide an example?

The UserDefaults's .plist file will still have an associated key/value pair in where the encoded value will be stored. The encoded value will be an array of bytes, be it plist or json. Using the JSONEncoder will, however, get a smaller footprint. The [Nested Objects Example](https://github.com/nmdias/DefaultsKit/blob/master/README.md#nested-objects) in the README file, for instance, will be about 30% smaller in json than in a plist.

**Comment by danlozano** [comment]
Hey :) 

- So UserDefaults value's can (well, must) be Plist values. So you can store a PLIST directly into UserDefaults without having to convert to and from Data. So you could store an Array of Dictionaries, with Strings in them for example, without having to convert to Data.

> The UserDefaults class provides convenience methods for accessing common types such as floats, doubles, integers, Booleans, and URLs. A default object must be a property list—that is, an instance of (or for collections, a combination of instances of): If you want to store any other type of object, you should typically archive it to create an instance of NSData. For more details, see Preferences and Settings Programming Guide.

- But I guess I just realized the problem. JSON/Plist Decoder/Encoder in Swift 4 skips the intermediate step of converting to a dictionary/array/plist/etc... and goes straight to converting it into Data. So I guess we couldn't use Codable to convert a custom model into "plist" models. So maybe it's just easier to convert to JSON data and be over with it.

- Oh and you make a good point about the size.

Hmmmmm 🤔 ... Just thinking out loud, thanks for the cool framework! Will def. use.

**Comment by danlozano** [comment]
To answer your original question, you CAN store and retrieve a PLIST value in UserDefaults without converting to Data, it's real simple. This is because UserDefaults is a PLIST behind the scenes.

let plist: [String : Any] = ["key" : bool, "otherKey" : "value"] <-- PLIST/Dictionary
userDefaults.setObject(plist, forKey: "key") <-- Store, without converting to Data

---

let plist: [String : Any] = userDefaults.getObject(forKey: "key") as! [String : Any] <-- Retrieve, without converting from Data

**Comment by nmdias** [comment]
You're right, that does work. 🙂

For a minute there I thought we wouldn't need the middleman. But we would still need do serialize and deserialize the object as a Dictionary.

```
Object -> Dictionary -> Plist -> Dictionary -> Object
Object -> Data -> Plist -> Data -> Object
```

**Comment by danlozano** [comment]
Yeah, that's what I just realized.

- Codable already does the conversion straight from Model to Data, if we wanted to store the PLIST directly we would need to manually convert from Model to PLIST dictionary as I think CODABLE does not give us that intermediate step.

- Also, as you say, JSON is more efficient.

SOO, good job 👍 ... Can't wait to use this!
