### ISSUE TITLE
Swift.EncodingError.Context(codingPath: [], debugDescription: "Top-level Data encoded as string JSON fragment.", underlyingError: nil)

### ISSUE THREAD

**Issue by niuxinhuai** [nmdias/DefaultsKit#21]
This was an accident when I converted the custom model using an archive to binary using "Defaults" for storage. This is a problem I recently used with Xcode 9.4.1, Swift 4.0. I didn't see this problem before using Xcode 9.2. The version of Defaults that I am using now is 0.0.8.

I also looked at this document "https://git.snooey.net/Mirrors/swift/blob/a8ba0772cd2f887c2b48549172d2c447140e06d8/stdlib/public/SDK/Foundation/JSONEncoder.swift"
I don't quite understand why this error caused my storage binary type to fail.

I hope you can help me.

Thanks

**Comment by nmdias** [comment]
Hi, @niuxinhuai 

I hope this is no longer an issue and that you were able to fix it. I'm sorry it took so long for the reply. If it's still something you'd like to discuss, please be so kind and re-open the issue and I will do my best to assist you.

Thank you 🙏
