### ISSUE TITLE
Xcode 12.0.1 & SPM

### ISSUE THREAD

**Issue by norbdev** [nmdias/DefaultsKit#29]
I get this error when I try to install DefaultsKit with SPM (Carthage works)

> because every version of DefaultsKit contains incompatible tools version and root depends on DefaultsKit 0.2.0, version solving failed.

**Comment by jtouzy** [comment]
Same error (Xcode 12 + SPM)
This topic talks about invalid characters in some files: https://developer.apple.com/forums/thread/650499
Maybe it can lead to something.

**Comment by lex-shvets** [comment]
Same :( Any update?

**Comment by norbdev** [comment]
+1

**Comment by nmdias** [comment]
Should be working now. Thank you.
