### ISSUE TITLE
how to initialise default with suitname ?

### ISSUE THREAD

**Issue by dipenshivlab** [nmdias/DefaultsKit#31]
I have App where I use custom keyboard extension and I want to share default with group identifires for that I need to initialise default with suit name how can we do this with DefaultsKit ?

**Comment by nmdias** [comment]
You can use the initializer to pass along your instance of UserDefaults:

```swift
public init(userDefaults: UserDefaults = UserDefaults.standard)
```

```swift
Defaults(userDefaults: .init(suiteName: "some"))
```

Thank you
