### ISSUE TITLE
if DEBUG typo

### ISSUE THREAD

**Issue by callumboddy** [nmdias/DefaultsKit#4]
I know this comment is annoying, I wouldn't normally raise for a nit but this wont work if in DEBUG.

Just noticed it in passing...

https://github.com/nmdias/DefaultsKit/blob/53aa9b788d30cb2edff21d6c7ea25bf31bd2a7f5/Sources/Defaults.swift#L92

**Comment by nmdias** [comment]
Thanks @callumboddy 😄
